### PR TITLE
Add support for .NET Standard 1.3 and .NET Framework 4.5.2

### LINKED ISSUE #6: Support .NET Standard 1.x
There seems to be no blocking issue in order to support .NET Standard 1.3 (or at least 1.5). That way we can support .NET Core 1.0 users.

I hope I can give it a try in the next couple of days.

Also take the opportunity to congrats @SteveSyfuhs for a great lib!

### PR DESCRIPTION
**Pull request by jorgebay**
Fixes #6.

### CODE REVIEW

**Comment by SteveSyfuhs** [comment]
These changes look good. Presumably the tests all pass?

**Comment by jorgebay** [comment]
All tests pass (ran on macOS and Windows), except for `TestParseClaims` which also fails on master.

**Comment by SteveSyfuhs** [comment]
Okay, that works for me. Claims parsing requires a specific compression function that is only available on Windows as far as I can find, and I can't be bothered to build a decompress algorithm.

**Comment by SteveSyfuhs** [comment]
Passed build and is uploaded to Nuget. Will take a few minutes for indexing to kick in, but it's there:

https://www.nuget.org/packages/Kerberos.NET/2.0.209.1

**Pull request merged**
