### PR TITLE
Feature/client tools

### PR DESCRIPTION
**Pull request by SteveSyfuhs**
### What's the problem?

The library is a little complicated to work with if you're just starting out. It has a fairly high barrier to entry when getting started, especially for complex setups. It would be helpful if client tools existed to make working with the cache and config files a lot easier.

- [ ] Bugfix
- [X] New Feature

### What's the solution?

Build out a set of tools that work against the cache and config files. In this PR there are a handful of useful commands wrapped in a REPL shell called "Bruce". The Bruce shell executable has a unique feature where you can rename it into one of the named commands and the command will be executable externally without going through the Bruce shell.

```
bruce> help

Commands

   help           Provides help information about commands.
   kconfig        Set or review configuration settings at the default path.
   kdestroy       Delete the ticket cache.
   kinit          Obtain a cache a Kerberos Ticket-Granting-Ticket.
   klist          Displays the current list of tickets in the cache.

bruce>kinit help
Usage: kinit principal
--principal=value [--realm=value] [-V] [-l value] [--lifetime=value] [-s value] [--start-time=value] [-f] [--forwardable] [-F] [--no-forwardable] [-p] [--proxiable] [-P] [--no-proxy] [-a] [-C] [-E] [--enterprise] [-v] [--validate] [-R] [--renew] 
[--renewable] [-r value] [--renewable-life=value] [-t value] [--keytab-name=value] [-k] [--use-keytab] [-n] [--anonymous] [-T value] [-c value] [--cache=value] [-S value] [--server=value] [-X value] [--ext=value] [-e value] [--enctypes=value]
[--extra-addresses=value] [-C value] [--cert=value] [--pk-user=value] [--kdc=value] [--kdc-hostname=value] [--request-pac] [--rst] [--reset] [-h] [--help] [-?]

   --principal=value                        The principal name to use otherwise uses the current system user.
   --realm=value                            Provide the realm name to authenticate against.
   -V                                       Display verbose output.
   -l value, --lifetime=value               Request a ticket with the provided lifetime.
   -s value, --start-time=value             Request a ticket starting from the provided time.
   -f, --forwardable                        Request a forwardable ticket.
   -F, --no-forwardable                     Do not request a forwardable ticket.
   -p, --proxiable                          Request a proxiable ticket.
   -P, --no-proxy                           Do not request a proxiable ticket.
   -a                                       Request a ticket with addresses.
   -C                                       Requests canonicalization of the ticket principal name.
   -E, --enterprise                         Treat the principal name as an enterprise name.
   -v, --validate                           Request the TGT be sent to the KDC for validation.
   -R, --renew                              Renew the requested TGT.
   --renewable                              Request a ticket that is renewable up to renewable-lifetime or infinite lifetime.
   -r value, --renewable-life=value         Request a ticket that is renewable up to the requested lifetime.
   -t value, --keytab-name=value            Obtain a ticket using the provided keytab.
   -k, --use-keytab                         Obtain a ticket using the keytab located in the default location.
   -n, --anonymous                          Request an anonymous ticket.
   -T value                                 Provide the name of a cache used to armor the current request.
   -c value, --cache=value                  Provide the name of a cache to store and retrieve tickets.
   -S value, --server=value                 Specify a service name to to use when getting tickets.
   -X value, --ext=value                    Pass values to Kerberos extensions.
   -e value, --enctypes=value               Specify the encryption types that should be used in preferred order.
   --extra-addresses=value                  Include additional addresses in the ticket request.
   -C value, --cert=value, --pk-user=value  Locate a certificate and use PKINIT to authenticate the user.
   --kdc=value, --kdc-hostname=value        Specify the KDC that should process this request.
   --request-pac                            Indicate whether a PAC should be requested during authentication.
   --rst, --reset                           Reset the connection cache.
   -h, --help, -?                           Help

bruce.exe -> kconfig.exe
bruce.exe -> kdestroy.exe
bruce.exe -> kinit.exe
bruce.exe -> klist.exe
```

 - [X] Includes unit tests
 - [ ] Requires manual test

### What issue is this related to, if any?

Rolls up to https://github.com/dotnet/Kerberos.NET/issues/169

### CODE REVIEW

**Comment by gfoidl** [comment]
Do you plan to make Bruce as .NET Core global tool?
Benefit would be easy to "install" and update via NuGet.

**Comment by SteveSyfuhs** [comment]
@gfoidl I hadn't even considered that. It's a great idea. I will add then in a follow up PR! Edit: easier than I thought. Will add it here.

**Comment by SteveSyfuhs** [comment]
Heh, this is pretty cool. Once I get it signed I'll publish it to nuget.org. 😁 Good call!

```
❯ dotnet tool install --global --add-source .\nupkg Bruce --version 4.5.8-g67a93246a1
You can invoke the tool using the following command: bruce
Tool 'bruce' (version '4.5.8-g67a93246a1') was successfully installed.

❯ bruce
  ____
 | __ ) _ __ _   _  ___ ___
 | |_) | |  | |_| | (_|  __/
 |____/|_|   \__,_|\___\___|


Command Line tooling for the Kerberos.NET library. (v4.5.8+67a93246a1)

(C) Copyright 2020 .NET Foundation

bruce>help

   User Default Values

         Version: 4.5.8+67a93246a1
   Configuration: C:\Users\stsyfuhs\AppData\Roaming\Kerberos.NET\krb5.conf

   Commands

   help           Provides help information about commands.
   kdestroy       Delete the ticket cache.
   kinit          Obtain a cache a Kerberos Ticket-Granting-Ticket.
   klist          Displays the current list of tickets in the cache.
```

**Comment by gfoidl** [comment]
Nice -- .NET Core Tools are really nice and easy to make. They made a brilliant job making this.

**Pull request merged**
