### PR TITLE
Fix for 32-bit key version override

### PR DESCRIPTION
**Pull request by simonbaas**
Fix for 32-bit key version override (for more information see http://web.mit.edu/kerberos/krb5-latest/doc/formats/keytab_file_format.html)

### CODE REVIEW

**Comment by SteveSyfuhs** [comment]
Nice change. Do you have a test file you can add to a unit test to verify this works?

**Comment by simonbaas** [comment]
I do have a "real" keytab file issued by the Kerberos server administrator but that file I cannot publish here and I'm unsure on how to create a test keytab file. I'm on a linux environment.

**Comment by SteveSyfuhs** [comment]
How did the administrator generate the file?

**Comment by simonbaas** [comment]
I will try to figure it out myself, otherwise I'll ask him on Monday.

**Comment by SteveSyfuhs** [comment]
Nice!

**Pull request merged**
